---
- name: DEPLOY AS3 DEC
  hosts: localhost
  connection: local
  gather_facts: no


  vars:
  
  vars_files:
    - ../creds/big_creds.yaml

  tasks:


    - name: Create a AS3 Declaration - Sandeep
      uri:
        url: https://18.134.162.22/mgmt/shared/appsvcs/declare
        user: "{{bigip_user}}"
        password: "{{bigip_pass}}"
        method: POST
        body: "{{ lookup('file','as3_test1.json') }}"
        force_basic_auth: yes
        status_code: 200
        body_format: json
        validate_certs: no
      register: as3_output



    - name: Debug AS3 output
      debug:
        msg: "My AS3 output {{ as3_output }}"
    - name: Search for content length
      debug:
        msg: "Content Length = {{as3_output.content_length}}"


...